# Generated by Django 3.0.5 on 2020-04-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodswing', models.IntegerField(choices=[(0, 'Very Hard'), (1, 'Hard'), (2, 'Normal'), (3, 'Good'), (4, 'Very Good')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
